# Generated by Django 2.2.4 on 2019-08-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190827_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.IntegerField(choices=[(-1, 'Vote up'), (1, 'Vote down')]),
        ),
    ]
