# Generated by Django 2.2.4 on 2019-08-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(max_length=100)),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superhero.Origin')),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superhero_sighting', to='superhero.Location')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_where', to='superhero.Power')),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_where', to='superhero.Origin')),
            ],
        ),
    ]
