# Generated by Django 2.2.4 on 2019-08-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[(1, 'On Hold'), (2, 'In Review'), (3, 'Published'), (4, 'Draft')], default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='origin',
            name='status',
            field=models.CharField(choices=[(1, 'On Hold'), (2, 'In Review'), (3, 'Published'), (4, 'Draft')], default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='sighting',
            name='status',
            field=models.CharField(choices=[(1, 'On Hold'), (2, 'In Review'), (3, 'Published'), (4, 'Draft')], default=3, max_length=2),
        ),
    ]
