# Generated by Django 2.2.4 on 2019-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0002_power_sighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='sighted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
