# Generated by Django 2.2.4 on 2019-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superhero', '0002_auto_20190822_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.IntegerField(choices=[(1, 'On Hold'), (2, 'In Review'), (3, 'Published'), (4, 'Draft')], default=3),
        ),
        migrations.AlterField(
            model_name='origin',
            name='status',
            field=models.IntegerField(choices=[(1, 'On Hold'), (2, 'In Review'), (3, 'Published'), (4, 'Draft')], default=3),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='status',
            field=models.IntegerField(choices=[(1, 'On Hold'), (2, 'In Review'), (3, 'Published'), (4, 'Draft')], default=3),
        ),
    ]
